[tool.poetry]
name = "diyims"
version = "0.0.0a1"
description = "A diy independent media services app that provides the modern version of the single person printing press."
authors = ["Douglas R Fix <douglasrfix@prairieobserver.com>"]
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/douglasrfix/diyims"
packages = [{include = "diyims", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.32.3"
aiosql = "^11.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
